### ISSUE TITLE
connection error while downloading seeta_fd_frontal_v1.0-c4619d06.bin

### ISSUE THREAD

**Issue by vijayendra-g** [TuXiaokang/pyseeta#11]
I was successfully able to install pyseeta  [ steps 1-4].
but getting the following error.  Looks like it is connection error while downloading seeta_fd_frontal_v1.0-c4619d06.bin. 

 is there a work around. I am using  ubuntu vm on amzon.

$ python test_opencv.py or test_pillow.py 
test detector:
Downloading: "http://198.13.45.221/files/seeta_fd_frontal_v1.0-c4619d06.bin" to /root/.pyseeta/models/seeta_fd_frontal_v1.0-c4619d06.bin
Traceback (most recent call last):
  File "/<PATH>/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/<PATH>/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/<PATH>/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/<PATH>/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/<PATH>/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/<PATH>/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/<PATH>/anaconda3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/<PATH>/anaconda3/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/<PATH>/anaconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_opencv.py", line 117, in <module>
    test_detector()
  File "test_opencv.py", line 38, in test_detector
    detector = Detector()
  File "/<PATH>/anaconda3/lib/python3.6/site-packages/pyseeta-0.4-py3.6.egg/pyseeta/detector.py", line 67, in __init__
    model_path = load_url(MODEL_URL)
  File "/<PATH>/anaconda3/lib/python3.6/site-packages/pyseeta-0.4-py3.6.egg/pyseeta/model_zoo.py", line 74, in load_url
    _download_url_to_file(url, cached_file, hash_prefix)
  File "/<PATH>/anaconda3/lib/python3.6/site-packages/pyseeta-0.4-py3.6.egg/pyseeta/model_zoo.py", line 80, in _download_url_to_file
    u = urlopen(url)
  File "/<PATH>/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/<PATH>/anaconda3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/<PATH>/anaconda3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/<PATH>/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/<PATH>/anaconda3/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/<PATH>/anaconda3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by TuXiaokang** [comment]
The reason is the web server was down. Now, it has been restarted.

**Comment by HandsLing** [comment]
@vijayendra-g do you download this file? can you share it to me? thx a lot

**Comment by TuXiaokang** [comment]
Sorry, the server has gone out of use. You can download the model files from original repo ( https://github.com/seetaface/SeetaFaceEngine/tree/master/FaceDetection) and rename it, 
then put it into `~/.pyseeta/models`.
