### ISSUE TITLE
RuntimeError: SeetaFaceEngine detector dynamic library libseeta_fd_lib.so can't find

### ISSUE THREAD

**Issue by zijing-wu** [TuXiaokang/pyseeta#12]
First, thank you for your work!

I followed the setup steps for installation and everything works fine. When I change to example directory and run 
`python test_opencv.py`
it throws RuntimeError.

> Traceback (most recent call last):
  File "test_opencv.py", line 25, in <module>
    from pyseeta import Detector
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/zijing/.local/share/virtualenvs/seetaface-cRn5R2_H/lib/python3.5/site-packages/pyseeta-0.4-py3.5.egg/pyseeta/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/zijing/.local/share/virtualenvs/seetaface-cRn5R2_H/lib/python3.5/site-packages/pyseeta-0.4-py3.5.egg/pyseeta/detector.py", line 36, in <module>
  File "/home/zijing/.local/share/virtualenvs/seetaface-cRn5R2_H/lib/python3.5/site-packages/pyseeta-0.4-py3.5.egg/pyseeta/config.py", line 49, in get_detector_library
  File "/home/zijing/.local/share/virtualenvs/seetaface-cRn5R2_H/lib/python3.5/site-packages/pyseeta-0.4-py3.5.egg/pyseeta/config.py", line 46, in get_library_raise
RuntimeError: SeetaFaceEngine detector dynamic library libseeta_fd_lib.so can't find

I am thinking if it has to do with new setup step needed with release v0.4.0. Could you help me on this? Thank you!

**Comment by Monarch1995** [comment]
I also encounter this problem,have you solved?

**Comment by TuXiaokang** [comment]
I have not to test pyseeta with virtualenvs.  Maybe u should try to build pyseeta without virtualenvs
