### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by soraciel** [TuXiaokang/pyseeta#13]
When i run `python setup.py install`

the output will be 

`Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from pyseeta import config
  File "C:\thesis\pyseeta\__init__.py", line 4, in <module>
    from pyseeta.detector import Detector
  File "C:\thesis\pyseeta\detector.py", line 38, in <module>
    detect_lib = cdll.LoadLibrary(lib_path)
  File "C:\Users\user-pc\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\user-pc\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application`

i've opened the detector.py and i found that the lib_path value is **seeta_fd_lib**  . Therefore, my hypothesis is s**eeta_fd_lib is not a valid Win32 application** according to the error. 

I have installed from seetaface itself or downloaded the pre-trained mode. But the result always `OSError: [WinError 193] %1 is not a valid Win32 application` 

Can you help me solving this problem? Thank you!

**Comment by TuXiaokang** [comment]
have you tried `Visual Studio 14 2015 Win32` instead of` Visual Studio 14 2015 Win64`?
